# Generated by Django 3.2 on 2023-05-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='post_id',
            new_name='post',
        ),
    ]
