# Generated by Django 3.2 on 2023-04-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_media_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.AddField(
            model_name='post',
            name='medias',
            field=models.ManyToManyField(to='api.Media'),
        ),
    ]
