# Generated by Django 3.2 on 2023-04-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230425_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='medias',
            field=models.ManyToManyField(null=True, to='api.Media'),
        ),
    ]
