# Generated by Django 3.2 on 2023-04-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_post_medias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='medias',
        ),
        migrations.AddField(
            model_name='media',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
            preserve_default=False,
        ),
    ]
